export const BID_MUTATIONS = {
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  SET_BID_ORIGINAL: 'SET_BID_ORIGINAL',
  SET_BID_UI: 'SET_BID_UI',
  SET_BID_MODIFIED: 'SET_BID_MODIFIED',
  SET_PROJECT_BIDS: 'SET_PROJECT_BIDS',
  SET_FREELANCER_BIDS: 'SET_FREELANCER_BIDS',
} as const;
