spring:
  application:
    name: PROJECT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/project_service
    username: postgres
    password: aryan
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


