import type { FreelancerBackend, FreelancerUI, FreelancerModified } from '../types/freelancer.types';

export const mapFreelancerBackendToUI = (backend: FreelancerBackend): FreelancerUI => ({
  freelancerId: backend.freelancerId,
  userId: backend.userId,
  name: backend.name,
  email: backend.email,
  skills: backend.skills ? backend.skills.split(',').map((s) => s.trim()).filter(Boolean) : [],
  rating: backend.rating || 0,
  completedProjects: backend.completedProjects || 0,
  availabilityStatus: backend.availabilityStatus || 'AVAILABLE',
  profileSummary: backend.profileSummary || '',
  portfolioLink: backend.portfolioLink || '',
  location: backend.location || '',
  profilePictureUrl: backend.profilePictureUrl || '',
  phoneNumber: backend.phoneNumber || '',
  socialLinks: backend.socialLinks || '',
  certifications: backend.certifications || '',
  languages: backend.languages || '',
  hourlyRate: backend.hourlyRate || '',
  education: backend.education || '',
  workExperience: backend.workExperience || '',
  additionalInfo: backend.additionalInfo || '',
  createdAt: new Date(backend.createdAt),
  updatedAt: new Date(backend.updatedAt),
});

export const mapFreelancerUIToModified = (ui: FreelancerUI): FreelancerModified => ({
  userId: ui.userId,
  name: ui.name,
  email: ui.email,
  skills: Array.isArray(ui.skills) ? ui.skills.join(', ') : ui.skills,
  availabilityStatus: ui.availabilityStatus,
  profileSummary: ui.profileSummary,
  portfolioLink: ui.portfolioLink,
  location: ui.location,
  profilePictureUrl: ui.profilePictureUrl,
  phoneNumber: ui.phoneNumber,
  socialLinks: ui.socialLinks,
  certifications: ui.certifications,
  languages: ui.languages,
  hourlyRate: ui.hourlyRate,
  education: ui.education,
  workExperience: ui.workExperience,
  additionalInfo: ui.additionalInfo,
});
