export const PROJECT_MUTATIONS = {
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  SET_PROJECT_ORIGINAL: 'SET_PROJECT_ORIGINAL',
  SET_PROJECT_UI: 'SET_PROJECT_UI',
  SET_PROJECT_MODIFIED: 'SET_PROJECT_MODIFIED',
  SET_ALL_PROJECTS: 'SET_ALL_PROJECTS',
  SET_OPEN_PROJECTS: 'SET_OPEN_PROJECTS',
} as const;
