export const FREELANCER_MUTATIONS = {
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  SET_PROFILE_ORIGINAL: 'SET_PROFILE_ORIGINAL',
  SET_PROFILE_UI: 'SET_PROFILE_UI',
  SET_PROFILE_MODIFIED: 'SET_PROFILE_MODIFIED',
  SET_ALL_FREELANCERS: 'SET_ALL_FREELANCERS',
  SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
} as const;
