export const AUTH_MUTATIONS = {
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  SET_TOKEN: 'SET_TOKEN',
  SET_USER_ORIGINAL: 'SET_USER_ORIGINAL',
  SET_USER_UI: 'SET_USER_UI',
  SET_USER_MODIFIED: 'SET_USER_MODIFIED',
  LOGOUT: 'LOGOUT',
} as const;
