export const CLIENT_MUTATIONS = {
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  SET_PROFILE_ORIGINAL: 'SET_PROFILE_ORIGINAL',
  SET_PROFILE_UI: 'SET_PROFILE_UI',
  SET_PROFILE_MODIFIED: 'SET_PROFILE_MODIFIED',
  SET_PROJECTS: 'SET_PROJECTS',
} as const;
