spring:
  application:
    name:
      api-gateway

  cloud:
    gateway:
      routes:
        - id: freelancer-user
          uri: lb://FREELANCER-USER
          predicates:
            - Path=/users/**
          filters:
            AuthFilter
        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/clients/**
          filters:
            AuthFilter

        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/projects/**
          filters:
            AuthFilter
      server:
        webflux:
          discovery:
            locator:
              enabled: true



server:
  port:
    8765

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG

